telegram:
  name: kingbbode-sample
  token: xxx
slack:
  token: xxx

line:
  bot:
    channel-token: SNhLPQkWDfSJz+EAdY9T+7d0Nk0AMu7NTBb5cYm1qB1FkOcmfU8zJ/UMpup5H5/uFDyq0K3RPUWbZwSQy998IuzAoVWyy7EJoUdUmCCfT+U2j/sdgiT1BSmPhU0R8Ie6fp0KMRRrhTpefShjDC2JmgdB04t89/1O/w1cDnyilFU=
    channel-secret: 459a48286789216b10ea47653ce2e038

debug: true
